# docker-compose.yml
version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../indicador-online-dash-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../indicador-online-dash-backend/.env
